### ISSUE TITLE
Creation of Air Quality Reporting Templates in R Markdown

### ISSUE THREAD

**Issue by nmsuzuki** [bcgov/air-zone-reports#1]
This issue is for a paid opportunity through the [BCDevExchange](https://bcdevexchange.org/). To apply, visit the [opportunity page](https://bcdevexchange.org/opportunities/cwu/opp-creation-of-air-quality-reporting-templates-in-r-markdown) and submit a proposal by 16:00 Pacific Time, Wednesday, February 20, 2019.

---

Produce parameterized report templates in R Markdown for future air zone reports. These templates will use objects produced by R code that has already been prepared to support the suite of air indicators by Environmental Reporting BC. PM2.5-related code can be found at https://github.com/bcgov/pm25-caaqs-indicator. Ozone code can be found at: https://github.com/bcgov/ozone-caaqs-indicator.  

Using the Georgia Strait Air Zone Report (2015-2017) as an example (https://www2.gov.bc.ca/assets/gov/environment/air-land-water/air/reports-pub/air-zone-reports/2014-2016/georgia_strait_air_zone_report_2014-2016_final.pdf), work will include the following: 

1. Ozone
(i) Run the ozone-caaqs-indicator analysis in https://github.com/bcgov/ozone-caaqs-indicator (branch: update-2018);
(ii) Use output from item 1(i) to recreate Figures 2 to 3 from example air zone report;
(iii) Use output from item 1(i) to create parameterized version of Table 2 from example air zone report using gt r package (https://github.com/rstudio/gt). 

2. PM2.5
(i) Run pm25-caaqs-indicator analysis in https://github.com/bcgov/pm25-caaqs-indicator (branch: update-2018);
(ii) Use output from item 2(i) to recreate Figures 4 and 5 from example air zone report;
(iii) Use output from item 2(i) to create parameterized version of Table 3 from example air zone report using gt r package

3. Parameterized Air Zone Reports
Create six (6) .Rmd air zone report templates that include:
(i) air zone map;
(ii) Figures 2-5 and Table 3 referenced above for each of six air zones.

The six templates can be based on a master parameterized report, with an ‘Air Zone’ parameter that can be set to one of the six B.C. Air Zones.

The result will be one .Rmd for each of the six air zones: Northeast, Central Interior, Southern Interior, Lower Fraser Valley, Georgia Strait and Coastal Air Zones. Each template will differ by title, air zone map, and air quality parameters (and resultant plots and tables) filtered by air zone.

4. Parameterized Air Zone Summary Report
Create .Rmd template of air zone summary report that includes 
(i)	Placeholder for introductory text;
(ii)	Air zone map, showing air zone names, boundaries and major population centres within individual air zones; 
(iii)	Table 1 from example air zone report;
(iv)	Air zone summary plot for 24-hour average and annual average PM2.5, and 8-hour average ozone;
(v)	Air zone/station CAAQS mgmt level map and achievement chart for both PM2.5 and ozone.

**Comment by nmsuzuki** [comment]
Hi, my name is Natalie Suzuki and I am the contact for this Code With Us opportunity. Please post any questions you have and I will do my best to respond promptly.

**Comment by Dpananos** [comment]
The link in 1 (i) is broken.  In order to submit a proposal, I'd like to know the contents of that link.  Thank you

**Comment by nmsuzuki** [comment]
There were a couple of broken links in the opportunity on BCDevExchange that have now been fixed. Thanks.

**Comment by steffilazerte** [comment]
Hello,
I was wondering if there's any flexibility in the expected date of completion (end of March 2019). Is it tied to the end fiscal, or could a date 2-4 weeks later be negotiated?
Thanks!

**Comment by nmsuzuki** [comment]
Thanks for your note -- yes, we are looking for completion by the end of the fiscal year end (Mar. 31/19).

**Comment by wchallenger** [comment]
Wondering if you could clarify how you are planning to compile R Markdown templates, for example in a single batch script or independently (e.g., within RStudio).  Also are the reports to share a custom reporting theme or is the default output themes acceptable?  I ask as implementation of custom themes differs via intended output format.

**Comment by nmsuzuki** [comment]
We will compile reports independently. Default pdf output is acceptable.

**Comment by karawoo** [comment]
Are the colored table cells required in the final PDF? gt supports coloring cells in HTML output, but not in LaTeX I believe.

**Comment by nmsuzuki** [comment]
Thanks for your question -- preference is for colored cells if possible.

**Comment by cwickham** [comment]
> The result will be one .Rmd for each of the six air zones

Do these need to be Rmarkdown (.Rmd)?  That is, will the code, figures or tables be edited at the airzone level?  An alternative might be markdown (.md) which would still allow edits to the text, but ensure consistency in the figure and table output (and keep the code that generated them in one place).

**Comment by nmsuzuki** [comment]
Thanks-figures and tables will be standard for all air zones (I.e. not edited for each air zone).

**Comment by 1186684BC** [comment]
What is the policy for GST? Is $6K inclusive of GST or can GST be charged on top?

**Comment by nmsuzuki** [comment]
Re: GST - GST is additional.

**Comment by nmsuzuki** [comment]
Re: gt colours -- we are flexible to different ideas to achieve desired output (i.e. coloured cells).

**Comment by nmsuzuki** [comment]
Thank you, everyone, for your interest in this opportunity. We had a total of 9 great proposals and have awarded the opportunity to @karawoo. If you have any questions about the process or feedback on your proposal, feel free to contact me privately (Natalie.Suzuki@gov.bc.ca).
