### ISSUE TITLE
Creation of Air Quality Reporting Templates in R Markdown

### ISSUE THREAD

**Issue by bcdevex** [bcgov/air-zone-reports#2]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-creation-of-air-quality-reporting-templates-in-r-markdown"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-creation-of-air-quality-reporting-templates-in-r-markdown">visit the opportunity page</a>.
The opportunity closes on <b>Wednesday, February 20th, 2019 at 16:00 PST</b>.</p>

**Comment by nmsuzuki** [comment]
Please see [this issue](https://github.com/bcgov/air-zone-reports/issues/1) which describes the scope of the work.

**Comment by bcdevex** [comment]
This opportunity has been assigned
